services:
  caijing18:
    build: .
    container_name: caijing18-app
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      # 将宿主机的 data 目录映射到容器内的 /app/data
      # 这样程序代码在 /app 下不受影响，数据库文件存在 data 中
      - ./data:/app/data
    restart: unless-stopped
